name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'typedoc.json'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run docs

      - name: Generate blog post from CHANGELOG
        run: |
          if [ -f scripts/changelog-to-blog.cjs ]; then
            node scripts/changelog-to-blog.cjs;
          fi

      - name: Commit documentation and blog changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs blog
          git commit -m "docs: 자동 문서/블로그 업데이트" || echo "No changes to commit"
          git push
